---
title: Chokladbollar
---

flowchart LR

subgraph " "
    direction LR
   A["3 dl havregryn"]
end

subgraph " "

    B[1 dl socker]
    C[2 tsp vaniljsocker]
    D["3 msk kakao \n (fin, fairtrade)" ]
    E["2 msk starkt kaffe" ]
end

A --> Step3["Mixa i mixer"]


Step3 --> Step1["Rör ihop"]
B --> Step1
C --> Step1
D --> Step1
E --> Step1


Step1 --> Step2["Rulla i finriven kokos/pärlsocker"]


