---
title: Korvbröd
---


flowchart LR



    subgraph " "
        A[25 g färsk jäst]
        B[2 1/2 dl kall mjölk]
        C[50 g rumstempererat smör]
        D[1/2 tsk salt]
        E[ca 5 dl vetemjöl]

    end


    B --> Step1["Baka \n 2 st bagetter => 4 st french hot dog bröd"]
    C --> Step1
    D --> Step1
    E --> Step1




